### ISSUE TITLE
Question about the result on KITTI 2015 and Sintel benchmark

### ISSUE THREAD

**Issue by MiaoJieF** [drinkingcoder/FlowFormer-Official#21]
From your correction results, I found that tile technology can effectively reduce EPE. Do you have any results on Sintel and KITTI 2015 test sets without tile technology? Since none of the other methods use Tile techniques, I was wondering how Flowformer would fare better under the same conditions.

**Comment by drinkingcoder** [comment]
The updated numbers reported in the Sintel benchmark, both training and test, are evaluated without tile. In the KITTI benchmark, we didn't provide the results because the shape of images in KITTI is quite different from training. Actually, we find that tiling with GMA/RAFT will significantly increase EPE because the information is incomplete especially near the border when tiling. However, FlowFormer now is more sensitive to image size due to the nature of transformers. We're trying to eliminate the image size bias of FlowFormer, which may further release FlowFormer's power.

**Comment by MiaoJieF** [comment]
Thanks for your detailed answer.
